remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 

title: EDM-Portfolio-Alian
description: This portfolio will contain copies of my Enterprise Data Management Lab Exercises.
